# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build App - Run Tests - Deploy Azure - aes-code-test-web

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Restore dependencies
        run: dotnet restore
        working-directory: src/PatternTester   
  
      - name: Build
        run: dotnet build --no-restore -c Release
        working-directory: src/PatternTester  
  
      - name: Test
        run: dotnet test --no-restore
        working-directory: src/PatternTester   

      - name: Publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}
        working-directory: src/PatternTester/PatternTester

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_79CDB1349BA643A4A968F0B9D7D55EEB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0440DBD454F944A59418B4F9E8E88D8F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0448D958A1E3410386A9D75C9769F090 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'aes-code-test-web'
          slot-name: 'Production'
          package: .
          